// other code...

const signUp = () => {
    // other code...
    const options = {
        emailRedirectTo: typeof window !== 'undefined' ? `${window.location.origin}/auth/callback?type=signup` : 'http://localhost:3000/auth/callback?type=signup',
        // other options...
    };
    // other code...
};

// other code...